### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by adrianmc** [adrianmc/simple-todos#1]
The POST request seems to go through, but we get this error in the console:

```
XMLHttpRequest cannot load http://startchart.azurewebsites.net/api/users. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
```

This SO question seems to have some leads: http://stackoverflow.com/questions/20035101/no-access-control-allow-origin-header-is-present-on-the-requested-resource

**Comment by hyperh** [comment]
For fetch there is an option to enable CORS, perhaps we need to do s/t similar

https://developer.mozilla.org/en-US/docs/Web/API/GlobalFetch/fetch

**Comment by hyperh** [comment]
http://stackoverflow.com/questions/5750696/how-to-get-a-cross-origin-resource-sharing-cors-post-request-working

```
 $.ajax({
            url: "http://localhost:8079/students/add/",
            type: "POST",
            crossDomain: true,
            data: JSON.stringify(somejson),
            dataType: "json",
            success: function (response) {
                var resp = JSON.parse(response)
                alert(resp.status);
            },
            error: function (xhr, status) {
                alert("error");
            }
        });
```

**Comment by hyperh** [comment]
https://azure.microsoft.com/en-us/documentation/articles/app-service-api-cors-consume-javascript/

Specifically https://acom.azurecomcdn.net/80C57D/cdn/mediahandler/docarticles/dpsmedia-prod/azure.microsoft.com/en-us/documentation/articles/app-service-api-cors-consume-javascript/20160531050151/corsinportal.png

Use * to allow all
