### ISSUE TITLE
Use localhost dev server when app is being run on local machine

### ISSUE THREAD

**Issue by adrianmc** [adrianmc/simple-todos#5]
Current `REMOTE_URL` refers to `http://startchart.azurewebsites.net/api`.

```
var REMOTE_URL = 'http://startchart.azurewebsites.net/api';
```

Ideally, it should detect whether or not the app is being run on a localhost. If it is, then it should point to `http://localhost:4000/api` instead.

**Comment by hyperh** [comment]
https://github.com/adrianmc/simple-todos/pull/6 will resolve this
